export const CATEGORY_MAP: Record<string, { color: string; icon: string; label: string }> = {
    food: { color: '#f97316', icon: 'restaurant', label: 'Food & Dining' },
    travel: { color: '#8b5cf6', icon: 'directions_car', label: 'Transport' },
    shopping: { color: '#f59e0b', icon: 'shopping_bag', label: 'Shopping' },
    groceries: { color: '#10b981', icon: 'shopping_cart', label: 'Groceries' },
    fuel: { color: '#06b6d4', icon: 'local_gas_station', label: 'Fuel' },
    entertainment: { color: '#ec4899', icon: 'movie', label: 'Entertainment' },
    bills: { color: '#6366f1', icon: 'receipt_long', label: 'Bills & Utilities' },
    health: { color: '#ef4444', icon: 'fitness_center', label: 'Health' },
    education: { color: '#3b82f6', icon: 'school', label: 'Education' },
    subscription: { color: '#a855f7', icon: 'subscriptions', label: 'Subscriptions' },
    salary: { color: '#4ade80', icon: 'account_balance_wallet', label: 'Salary' },
    transfer: { color: '#60a5fa', icon: 'swap_horiz', label: 'Transfer' },
    person_sent: { color: '#e5e7eb', icon: 'send', label: 'Sent to Person' },
    person_received: { color: '#4ade80', icon: 'payments', label: 'Received' },
    uncategorized: { color: '#6b7280', icon: 'help_outline', label: 'Uncategorized' },
};
