export const CATEGORY_MAP: Record<string, { color: string; icon: string; label: string }> = {
    person_sent: { color: '#e5e7eb', icon: 'send', label: 'Sent to Person' },
    person_received: { color: '#4ade80', icon: 'payments', label: 'Received from Person' },
    food: { color: '#9ca3af', icon: 'restaurant', label: 'Food & Dining' },
    travel: { color: '#9ca3af', icon: 'directions_car', label: 'Transport' },
    shopping: { color: '#f3f4f6', icon: 'shopping_bag', label: 'Shopping' },
    groceries: { color: '#9ca3af', icon: 'shopping_cart', label: 'Groceries' },
    fuel: { color: '#9ca3af', icon: 'local_gas_station', label: 'Fuel' },
    subscription: { color: '#9ca3af', icon: 'subscriptions', label: 'Subscriptions' },
    entertainment: { color: '#9ca3af', icon: 'movie', label: 'Entertainment' },
    bills: { color: '#9ca3af', icon: 'receipt_long', label: 'Bills' },
    health: { color: '#9ca3af', icon: 'fitness_center', label: 'Health' },
    salary: { color: '#4ade80', icon: 'account_balance_wallet', label: 'Salary' },
    uncategorized: { color: '#6b7280', icon: 'help_outline', label: 'Uncategorized' },
};
